import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Button from 'react-bootstrap/Button';


const CLIENT_ID = "69abf0dd9dba4bc79ff7521a1a98d964"; 
const SPOTIFY_AUTHORIZE_ENDPOINT = "https://accounts.spotify.com/authorize";
const REDIRECT_URL_AFTER_LOGIN = "http://localhost:3000/search";
const SPACE_DELIMITER = "%20";
const SCOPES = [
  "user-read-currently-playing",
  "user-read-playback-state",
  "playlist-read-private",
  "user-read-private",
  "user-read-email",
  "user-top-read",
  "user-read-recently-played",
];
const SCOPES_URL_PARAM = SCOPES.join(SPACE_DELIMITER);

const handleLogin = () => {
  window.location = `${SPOTIFY_AUTHORIZE_ENDPOINT}?client_id=${CLIENT_ID}&redirect_uri=${REDIRECT_URL_AFTER_LOGIN}&scope=${SCOPES_URL_PARAM}&response_type=token&show_dialog=true`;
};


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nostalgify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <h1>Similarfy</h1>
        <Button variant="success" onClick={handleLogin} className = "loginbtn">Login</Button>


      </main>

      <footer className={styles.footer}>
        <a>
          Made by Odi
        </a>
      </footer>
    </div>
  )
}
